menu:
  Home: /
  Archive: /archive/
  GitHub: https://github.com/bmwant/bmwlog-static
  RSS: /atom.xml


copyright:
  url: https://twitter.com/bmwant


google_analytics: "G-VHC1F2BSES"
comments: true
